import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import {apiRouter} from "./routes/api.js";
import {errorHandler,notFound} from "./middleware/errorHandler.js";
import {config} from "./config.js";
const app=express();app.set("trust proxy",1);app.use(helmet());app.use(cors({origin:config.corsOrigin,credentials:true}));app.use(express.json({limit:"100kb"}));app.use(cookieParser());
app.get("/health",(_req,res)=>res.json({status:"ok",service:"talentbridge-authorization-api"}));app.use("/api",apiRouter);app.use(notFound);app.use(errorHandler);
app.listen(config.port,()=>console.log(`TalentBridge authorization API listening on http://localhost:${config.port}`));