CREATE TYPE "UserRole" AS ENUM ('STUDENT','COMPANY','ADMIN');
CREATE TYPE "ApplicationStatus" AS ENUM ('APPLIED','REVIEWING','ACCEPTED','REJECTED','WITHDRAWN');
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" VARCHAR(180) NOT NULL,"passwordHash" VARCHAR(255) NOT NULL,"role" "UserRole" NOT NULL,"name" VARCHAR(120) NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Student" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"university" VARCHAR(160) NOT NULL,"graduationYear" INTEGER NOT NULL,CONSTRAINT "Student_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Company" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"companyName" VARCHAR(160) NOT NULL,"website" VARCHAR(255),CONSTRAINT "Company_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Internship" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"title" VARCHAR(160) NOT NULL,"description" TEXT NOT NULL,"location" VARCHAR(160) NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Internship_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Application" ("id" TEXT NOT NULL,"internshipId" TEXT NOT NULL,"studentId" TEXT NOT NULL,"status" "ApplicationStatus" NOT NULL DEFAULT 'APPLIED',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Application_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RefreshToken" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"tokenHash" CHAR(64) NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_role_isActive_idx" ON "User"("role","isActive");
CREATE UNIQUE INDEX "Student_userId_key" ON "Student"("userId");
CREATE UNIQUE INDEX "Company_userId_key" ON "Company"("userId");
CREATE INDEX "Internship_companyId_isActive_idx" ON "Internship"("companyId","isActive");
CREATE UNIQUE INDEX "Application_studentId_internshipId_key" ON "Application"("studentId","internshipId");
CREATE INDEX "Application_studentId_status_idx" ON "Application"("studentId","status");
CREATE INDEX "Application_internshipId_status_idx" ON "Application"("internshipId","status");
CREATE UNIQUE INDEX "RefreshToken_tokenHash_key" ON "RefreshToken"("tokenHash");
CREATE INDEX "RefreshToken_userId_revokedAt_idx" ON "RefreshToken"("userId","revokedAt");
CREATE INDEX "RefreshToken_expiresAt_idx" ON "RefreshToken"("expiresAt");
ALTER TABLE "Student" ADD CONSTRAINT "Student_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Company" ADD CONSTRAINT "Company_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Internship" ADD CONSTRAINT "Internship_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_internshipId_fkey" FOREIGN KEY ("internshipId") REFERENCES "Internship"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RefreshToken" ADD CONSTRAINT "RefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;